// o is an open passage where walls cannot be placed.
// Row and column limits count player walls only, including across separate corridors.
// Keep these IDs stable so existing browser progress remains compatible.
export const CHALLENGE_LEVELS = [
  {
    id: 'challenge-crossroads',
    title: '两侧牵制',
    chapter: '挑战 · 统筹',
    difficulty: 'challenge',
    budget: 4,
    rowLimit: 1,
    columnLimit: 1,
    description: '八个出口分居蓝线两侧。每行、每列只能放一堵墙，左右两边需要一起安排。',
    hint: '先数清每片连通空地接触蓝线的次数。处理一侧时，想一想会占用另一侧需要的哪一行。',
    rows: [
      '#########',
      '#..oSo..#',
      '#o##*##o#',
      '#..o*o..#',
      '#o##*##o#',
      '#..o*o..#',
      '#o##*##o#',
      '#..oTo..#',
      '#########',
    ],
  },
  {
    id: 'challenge-inner-court',
    title: '围廊里的取舍',
    chapter: '挑战 · 分配',
    difficulty: 'challenge',
    budget: 4,
    rowLimit: 2,
    columnLimit: 1,
    description:
      '蓝线围住七个出入口。每列只有一个名额，同一行最多两堵墙；一个岔口的选择会影响整座围廊。',
    hint: '把通道看成连接多个出口的树。墙可以拆开树，也可以封住出口；比较两种做法占用的列。',
    rows: [
      '#########',
      '#S....oT#',
      '#*##o##*#',
      '#*....o*#',
      '#*##o##*#',
      '#*.....*#',
      '#*##o##*#',
      '#*******#',
      '#########',
    ],
  },
  {
    id: 'challenge-offset',
    title: '错位的岔口',
    chapter: '挑战 · 变通',
    difficulty: 'challenge',
    budget: 4,
    rowLimit: 2,
    columnLimit: 1,
    description: '连接上下的岔口错开了，其中一处还禁止筑墙。用四堵墙，重新分配各个出口的归属。',
    hint: '不能筑墙的交汇点会一直连通。尝试保留它，让相连的分支只通向一个蓝色格子。',
    rows: [
      '#########',
      '#S.....T#',
      '#*#o###*#',
      '#*...o.*#',
      '#*###o#*#',
      '#*.....*#',
      '#*##o##*#',
      '#*******#',
      '#########',
    ],
  },
  {
    id: 'challenge-hidden-bridge',
    title: '桥后还有桥',
    chapter: '挑战 · 环路',
    difficulty: 'challenge',
    budget: 4,
    rowLimit: 1,
    columnLimit: 2,
    description:
      '内环、横桥与六个出口彼此相连。每行只能放一堵墙，断开一条近路之后，远处可能仍然相通。',
    hint: '先跟踪整片连通区域，不只盯着眼前的反例。环的一边被切断，另一边或横桥可能仍在连接出口。',
    rows: [
      '#########',
      '#So...oT#',
      '#*#...#*#',
      '#*o...o*#',
      '#*#.#.#*#',
      '#*o...o*#',
      '#*#####*#',
      '#*******#',
      '#########',
    ],
  },
  {
    id: 'challenge-interlocked',
    title: '环环相扣',
    chapter: '挑战 · 综合',
    difficulty: 'challenge',
    budget: 5,
    rowLimit: 1,
    columnLimit: 2,
    description:
      '上下两座横桥把内环连成一张网。五堵墙分散在不同的行，同一列最多两堵；每次落墙都要顾及全局。',
    hint: '设想放完墙之后，各个出口属于哪些互不相通的区域。再倒推边界，检查是否有横向或纵向通道穿过它。',
    rows: [
      '#########',
      '#So...oT#',
      '#*#...#*#',
      '#*o...o*#',
      '#*#...#*#',
      '#*o...o*#',
      '#*#####*#',
      '#*******#',
      '#########',
    ],
  },
];
